name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      # Set mock environment variables for build process
      GOOGLE_CLOUD_CREDENTIALS: '{"type":"service_account","project_id":"mock-project-id","private_key_id":"mock","private_key":"mock","client_email":"mock@example.com"}'
      GOOGLE_CLOUD_PROJECT_ID: 'mock-project-id'
      GOOGLE_TTS_VOICE_NAME: 'en-AU-Standard-A'
      GOOGLE_TTS_LANGUAGE_CODE: 'en-AU'
      GOOGLE_STT_LANGUAGE_CODE: 'en-AU'
      GOOGLE_STT_MODEL: 'latest_long'
    
    steps:
      - name: Check for Vercel token
        id: check_token
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "VERCEL_TOKEN not found. Skipping deployment."
            echo "has_token=false" >> $GITHUB_OUTPUT
          else
            echo "VERCEL_TOKEN found. Proceeding with deployment."
            echo "has_token=true" >> $GITHUB_OUTPUT
          fi
      
      - uses: actions/checkout@v3
        if: steps.check_token.outputs.has_token == 'true'
      
      - name: Install Vercel CLI
        if: steps.check_token.outputs.has_token == 'true'
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        if: steps.check_token.outputs.has_token == 'true'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        if: steps.check_token.outputs.has_token == 'true'
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        if: steps.check_token.outputs.has_token == 'true'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 